### ISSUE TITLE
Create a native JPMS module descriptor

### ISSUE THREAD

**Issue by bravehorsie** [eclipse-ee4j/jaf#13]
JAXB API uses activation-api as its dependency and is forced to use it as an automatic module or from classpath  because of missing a module-info.java descriptor file.

**Comment by bshannon** [comment]
A module-info.java won't be created until Jakarta EE 9 requires Java SE 9 or later.
In the mean time, an Automatic-Module-Name of jakarta.activation has been declared
in the 1.2.1 release.

**Comment by SebKister** [comment]
Extracts of interview in JAXenter "Richard Monson-Haefel: I think Jakarta EE should become much more modular and that will be accomplished through a simpler, more flexible programming model as well as Java SE Modules. Modularity, both in terms of the programming model and deployment, is the best way to accommodate not just cloud-native but all types of deployments and runtimes." ...."Jakarta EE 9 will begin the transition to a simpler, lighter, and more flexible platform but that’s not going to be ready until the middle or late next year."
Meanwhile (SE 11 and later) there will be no way of using JAXB( as it uses activation-api ) in a modular deployment using  jlink as it does not accept Automatic-Module.

**Comment by AlanBateman** [comment]
This is mostly an issue for those looking to create a run-time image containing the java.xml.bind module. It was easy to do this with JDK 9 or JDK 10 because java.activation was an explicit module in Java SE 9 and 10. It won't be possible with JDK 11 or newer until java.activation is an explicit module.

**Comment by oleg-nenashev** [comment]
It seems to impact us in the Jenkins project. We have some loading issues in one of our test tools when we run Maven Surefire in Java 8 with `-jvm` flag pointing to Java 11 ([JENKINS-55146](https://issues.jenkins-ci.org/browse/JENKINS-55146)).

Updating to JAX 1.2.1 seems to solve the issue somehow, but in such case we get into JAXB issues. Custom JAXB build would likely do the job, but there are other dependencies on the module

**Comment by namannigam** [comment]
To second @AlanBateman , here is a [similar question on StackOverflow.](https://stackoverflow.com/questions/53806586/is-it-possible-to-use-jlink-on-jdk-11-to-make-a-runtime-including-the-java-se-ee)

**Comment by swpalmer** [comment]
Is the module name change required? Yet another breaking change will not be fun!  I'd like to be able to use JAXB again some day.  Why weren't the Java SE EE modules kept in modularized form when they were removed from the JDK????  This is causing a world of pain for anyone trying to migrate to JDK 11 or beyond.

**Comment by bshannon** [comment]
Yes, this is a bigger mess than we would've liked.

I proposed a [set of options for how to handle the module names](https://www.eclipse.org/lists/ee4j-pmc/msg01195.html).

The PMC [chose option #1 - use jakarta.* for all module names](https://github.com/eclipse-ee4j/ee4j/issues/34).  That's why the module name changed.  This introduced an incompatibility with those modules that were included in JDK 9.

We will update all these modules to have complete module descriptors, and possibly introduce aggregator modules for compatibility, but that's just not a priority right now.

**Comment by swpalmer** [comment]
Okay, if the module name is changed and aggregator modules are used for backward compatibility the change will be tolerable.  But...
Why is it that things are left completely broken and it's "just not a priority right now"?
What happened that caused the backwards step that broke (de-modularized) the modules?
Did nobody bother to think how much that breaks existing workflows and prevents adoption of JDK 11+?

I was all prepared to depend on an external module for what was removed in JDK 11 - we had plenty of warning about that... except there is no external module!  You can't add to the module path and continue on as before.  Cleaning up the mess should be the first priority IMO.

**Comment by bshannon** [comment]
Sorry, there are only so many hours in a day.  First priority is Eclipse GlassFish 5.1 release.

**Comment by Tibor17** [comment]
@oleg-nenashev 
Do we have any problem with Surefire?
After time you made some changes and updated `activation jar` and maybe more. What has changed? How can I help?

**Comment by oleg-nenashev** [comment]
@Tibor17 I cannot say for sure that the problem is with Maven Surefire itself. The issue on our side is [JENKINS-55146](https://issues.jenkins-ci.org/browse/JENKINS-55146), and finally I had to revert the update due to this issue.


Summary of what we hit in Jenkins:

* We have a [Plugin Compatibility Tester](https://github.com/jenkinsci/plugin-compat-tester) for verifying Jenkins plugin compatibility. We recently updated this tool to run Maven Surefire tests with Java 11
* The tool runs in Docker or locally
* For Docker we consistently see crashes in Surefire while it tries to read the `java.activation.jar`. It happens when Surefire runs with JDK8 (`-jvm` and `-argLine` used to pass Java 11 for tests) AND when it runs fully with JDK11. Sample log is below. There are 3 entries which randomly appear in the Surefire crash log
* I would have assumed an issue with Debian used in the Docker image (like [SUREFIRE-1588](https://issues.apache.org/jira/browse/SUREFIRE-1588)), but I was able to reproduce the issue on MacOS and OpenJDK. Happens randomly there


```
+ echo 'Found Maven Surefire dump file: /pct/tmp/work/credentials/target/surefire-reports/2018-12-21T14-52-38_640-jvmRun1.dumpstream'
+ cat /pct/tmp/work/credentials/target/surefire-reports/2018-12-21T14-52-38_640-jvmRun1.dumpstream
# Created on 2018-12-21T14:52:39.364
Corrupted stdin stream in forked JVM 1. Stream 'Error occurred during initialization of boot layer'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'Error occurred during initialization of boot layer'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:469)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:191)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:158)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:87)
	at java.lang.Thread.run(Thread.java:748)


# Created on 2018-12-21T14:52:39.366
Corrupted stdin stream in forked JVM 1. Stream 'java.lang.module.FindException: Error reading /pct/jdk11-libs/javax.activation.jar'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'java.lang.module.FindException: Error reading /pct/jdk11-libs/javax.activation.jar'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:469)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:191)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:158)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:87)
	at java.lang.Thread.run(Thread.java:748)


# Created on 2018-12-21T14:52:39.366
Corrupted stdin stream in forked JVM 1. Stream 'Caused by: java.util.zip.ZipException: zip END header not found'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'Caused by: java.util.zip.ZipException: zip END header not found'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:469)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:191)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:158)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:87)
	at java.lang.Thread.run(Thread.java:748)
```

The issue happens in the test tool only, so it is not a blocker for Java 11 support in Jenkins. We also want to eventually use jlink in some cases, but so far we just bundle JARs in Docker images and research options to create a JAXB Plugin for WAR files to retain the Java 8 user experience there ([JENKINS-51965](https://issues.jenkins-ci.org/browse/JENKINS-51965)).

**Comment by Tibor17** [comment]
@oleg-nenashev 
There is very simple answer to say.
Every time user can see a dump saying that some stream is corrupted, it means that the test running in the forked JVM prints lines in native `System.out`. Surefire normally sets the proxy PrintStream via `System.setOut` but in some cases some frameworks use `FileDescriptor.out` or they get very early access to `System.out` during the boot time and surefire identified it as a corruption of the stream.

I introduced the dump file because of this.
We had many problems with users and this was the way to explain that the user has to fix it on his side.
We only provided all information of the error but the fix is not in our hands.

Once the stream is corrupted the VM may be killed by itself and the test set is incomplete and VM exited with error code `1` ans the Maven build consequently fails.

**Comment by nigredo-tori** [comment]
GlassFish 5.1 has been out for quite some time already. Is there any progress on this?

**Comment by bshannon** [comment]
Sorry, no, spending all my time on the Jakarta EE 8 release.

**Comment by zimmi** [comment]
Now that Jakarta EE 8 has been released, is this back on the table?

**Comment by bshannon** [comment]
The next priority is to get the Jakarta Activation spec approved through the
Jakarta EE Specification Process.  Hopefully I'll get back to this soon.

**Comment by zimmi** [comment]
Thank you for keeping us updated, your work is very much appreciated! :)

**Comment by bshannon** [comment]
I've created a jakarta.activation module descriptor for the Jakarta Activation 1.2.2 release.
