### ISSUE TITLE
package-list and element-list are missing on the root of the Javadoc

### ISSUE THREAD

**Issue by tquadrat** [eclipse-ee4j/jaf#61]
I would like to link the documentation for Java Activation Framework with the Javadoc of my  own library project, just for convenience reasons.

Usually, you do this with Javadoc's `-link` option and the URL for the root of the target Javadoc documentation; in this case, I assume it is [https://eclipse-ee4j.github.io/jaf/docs/api/jakarta.activation/](https://eclipse-ee4j.github.io/jaf/docs/api/jakarta.activation/). But in order to work, it is required that this folder contains a `package-list` and/or an `element-list` file; they are generated by Javadoc together with the HTML and contain the names of the packages and modules that are documented.

I assume that the file(s) will just not be copied when the Javadoc is published. This may be intentional, although it would not be funny if so …

**Comment by lukasj** [comment]
this is caused by switching the build to use JDK11. The thing is that javadoc tool on JDK 11 does not create `package-list` file, it only creates `element-list` file, see https://eclipse-ee4j.github.io/jaf/docs/api/element-list (the root is `https://eclipse-ee4j.github.io/jaf/docs/api/`). If this `element-list` is not enough for you, feel free to reopen this.

**Comment by tquadrat** [comment]
But element-list wasn’t there as well …

That’s why I wrote in the subject of the entry "package-list and element-list are missing on the root of the Javadoc“ …

--
Thomas Thrien
Godefriedstraße 24
Niederhofen
44265 Dortmund
Allemagne

Tel. +49 231 7285456
Mobil +49 171 5289503

email thomas.thrien@tquadrat.org

Geo 51° 27' 52" N 7° 29' 59" E

PGP Fingerprint C9AF 8B82 1B34 FE4B ED90  018B 3A12 EE78 7A30 0D21

Es heißt, der Klügere gibt nach. Doch wenn die Klügeren immer nachgeben, dann passiert nur noch, was die Dummen wollen …


Of course it has a meaning when a black cat crosses your way from left to right …
It means, that the cat, coming from your left, wants to go somewhere right from you …


You do not need to be a carpenter to see that the table rocks.

**Comment by lukasj** [comment]
[the repo of the web](https://github.com/eclipse-ee4j/jaf/blob/gh-pages/docs/api/element-list) says, that the file was created on Oct 22, 2020 and no modifications were done to it since then....

But what matters to me is if it works for you now or if you need to have `package-list` file available as well. For the latter case, I need to know JDK (javadoc tool version) you use and the full command being executed to verify that simple copy of `element-list` to `package-list` really workarounds the problem.

**Comment by tquadrat** [comment]
Attn: Lukas Jungmann

Hi Lukas,

first I need to apologize for the rude response in my previous email; I did not get your intention to help.

The Javadoc version I am using is „javadoc 15.0.1“, and that does not need package-list, element-list is sufficient for it.

That brings me to the next apology: I looked for {package|element}-list at the path „https://eclipse-ee4j.github.io/jaf/docs/api/jakarta.activation/“, not at „https://eclipse-ee4j.github.io/jaf/docs/api/“ where it is really. After changing the link parameter on the Javadoc call to the correct path, everything worked as a charm.

Thank you very much for your support on this!!

Kind regards

--
Thomas Thrien
Godefriedstraße 24
Niederhofen
44265 Dortmund
Allemagne

Tel. +49 231 7285456
Mobil +49 171 5289503

email thomas.thrien@tquadrat.org

Geo 51° 27' 52" N 7° 29' 59" E

PGP Fingerprint C9AF 8B82 1B34 FE4B ED90  018B 3A12 EE78 7A30 0D21

Es heißt, der Klügere gibt nach. Doch wenn die Klügeren immer nachgeben, dann passiert nur noch, was die Dummen wollen …


Of course it has a meaning when a black cat crosses your way from left to right …
It means, that the cat, coming from your left, wants to go somewhere right from you …


You do not need to be a carpenter to see that the table rocks.
